version: "3"
services:
  cesi-backend:
    image: daocloud.io/weicang/cesi:backend-2019.1006.01
    container_name: cesi-backend
    restart: on-failure
    volumes:
      - "./cesi.conf.toml:/etc/cesi.conf.toml:ro"
    ports:
      - 15000:5000

  cesi-frontend:
    image: daocloud.io/weicang/cesi:frontend-2019.1006.02
    container_name: cesi-frontend
    restart: on-failure
    ports:
      - "13000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - cesi-backend

  products.example.com:
    image: ef9n/supervisord:${SUPERVISOR_TAG}
    restart: on-failure
    volumes:
      - "./.docker/supervisor/confs/conf.d:/etc/supervisor/conf.d"
      - "./.docker/supervisor/products_supervisord.conf:/etc/supervisor/supervisord.conf"
      - "./.docker/supervisor/bin/:/opt/cesi-dev/bin"
      - "/tmp/cesi-dev/logs/products/:/opt/cesi-dev/logs"
    ports:
      - "9004:9001"

  analysis.example.com:
    image: ef9n/supervisord:${SUPERVISOR_TAG}
    restart: on-failure
    volumes:
      - "./.docker/supervisor/confs/conf.d:/etc/supervisor/conf.d"
      - "./.docker/supervisor/analysis_supervisord.conf:/etc/supervisor/supervisord.conf"
      - "./.docker/supervisor/bin/:/opt/cesi-dev/bin"
      - "/tmp/cesi-dev/logs/analysis/:/opt/cesi-dev/logs"
    ports:
      - "9002:9001"

  monitoring.example.com:
    image: ef9n/supervisord:${SUPERVISOR_TAG}
    restart: on-failure
    volumes:
      - "./.docker/supervisor/confs/conf.d:/etc/supervisor/conf.d"
      - "./.docker/supervisor/monitoring_supervisord.conf:/etc/supervisor/supervisord.conf"
      - "./.docker/supervisor/bin/:/opt/cesi-dev/bin"
      - "/tmp/cesi-dev/logs/monitoring/:/opt/cesi-dev/logs"
    ports:
      - "9003:9001"
